on:
  schedule:
    # https://crontab.guru/once-a-day
    - cron: 0 0 * * *
  workflow_dispatch: {}

name: Stats
jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/app-stats-action@v1.x
        id: stats
        with:
          id: ${{ secrets.ALL_CONTRIBUTORS_APP_ID }}
          private_key: ${{ secrets.ALL_CONTRIBUTORS_APP_PRIVATE_KEY }}
      - run: "echo installations: '${{ steps.stats.outputs.installations }}'"
      - run: "echo most popular repositories: '${{ steps.stats.outputs.popular_repositories }}'"
      - uses: logflare/action@v1
        with:
          api_key: ${{ secrets.LOGFLARE_API_KEY }}
          source_id: ${{ secrets.LOGFLARE_SOURCE_ID }}
          message: "stats: ${{ steps.stats.outputs.installations }} / ${{ steps.stats.outputs.repositories }}"
          metadata: |
            {
              "num_installations": ${{ steps.stats.outputs.installations }},
              "num_repositories": ${{ steps.stats.outputs.repositories }},
              "num_suspended_installations": ${{ steps.stats.outputs.suspended_installations }}
            }
